name: Automatically Integretion

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install requeirments package
        run: |
          pip install --upgrade
          pip install -r ./requeirments.txt

      - name: pep8, pylint testing
        run: python3 ./test.py
