name: ssh connect

on: [push]

jobs:
  ssh-connect:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Push
        uses: ErenKrt/ssh-push@1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
      
      - name: test dir
        run: |
          ssh_test.sh
      
